#!/usr/bin/env python3
"""Regenerate the favicon assets in static/ from one set of numbers.

The icon is the header's brand mark (templates/base.html, .brand-mark): a
rounded square holding a chevron pressing down onto a floor line — the library
compressed against a limit it may not pass, which is the whole job. The header
draws it as a thin outline in the current text color; a favicon is 16px on
unknown browser chrome, so this fills the square instead and knocks the
chevron and floor out of it in white.

Both the SVG and the raster sizes come from the constants below, so they can
never drift apart. Run it after changing any of them:

    python3 tools/make_favicon.py
"""
from pathlib import Path

from PIL import Image, ImageDraw

OUT = Path(__file__).resolve().parent.parent / "static"

# Geometry on a 0-1 square, taken from the brand mark's 24-unit viewBox with
# its 3-unit margin removed so the icon bleeds to the edge.
RADIUS = 0.22            # corner radius
CHEVRON = ((0.275, 0.283), (0.5, 0.483), (0.725, 0.283))
CHEVRON_STROKE = 0.108
FLOOR_Y = 0.725
FLOOR_X = (0.275, 0.725)
FLOOR_STROKE = 0.117     # the floor is the limit: a touch heavier

# Clay, the brand's own hue (--border-warning), a step deeper so it holds up
# against both a light and a dark browser tab. The knockout takes the app's
# warm off-white rather than pure white.
INK = "#b57f56"
LINE = "#fbf7f1"

SIZES = (16, 32, 48, 64, 128, 256)


def draw(px: int) -> Image.Image:
    """The mark at `px`, supersampled 8x so the corners and caps stay smooth."""
    s = px * 8
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rounded_rectangle((0, 0, s - 1, s - 1), radius=RADIUS * s, fill=INK)
    # PIL polylines have butt caps and mitred-ish joints; round every vertex by
    # stamping a disc of the stroke's radius over it.
    pts = [(x * s, y * s) for x, y in CHEVRON]
    w = CHEVRON_STROKE * s
    d.line(pts, fill=LINE, width=round(w), joint="curve")
    for cx, cy in pts:
        d.ellipse((cx - w / 2, cy - w / 2, cx + w / 2, cy + w / 2), fill=LINE)
    half = FLOOR_STROKE * s / 2
    cy = FLOOR_Y * s
    d.rounded_rectangle((FLOOR_X[0] * s, cy - half, FLOOR_X[1] * s, cy + half),
                        radius=half, fill=LINE)
    return img.resize((px, px), Image.LANCZOS)


def svg() -> str:
    """The same mark as vector, for browsers that prefer it (and any size)."""
    chevron = " ".join(f"{x * 100:.1f} {y * 100:.1f}" for x, y in CHEVRON)
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">\n'
        '  <!-- Generated by tools/make_favicon.py — edit that, not this. -->\n'
        f'  <rect width="100" height="100" rx="{RADIUS * 100:.0f}" fill="{INK}"/>\n'
        f'  <polyline points="{chevron}" fill="none" stroke="{LINE}"'
        f' stroke-width="{CHEVRON_STROKE * 100:.1f}"'
        ' stroke-linecap="round" stroke-linejoin="round"/>\n'
        f'  <line x1="{FLOOR_X[0] * 100:.1f}" y1="{FLOOR_Y * 100:.1f}"'
        f' x2="{FLOOR_X[1] * 100:.1f}" y2="{FLOOR_Y * 100:.1f}"'
        f' stroke="{LINE}" stroke-width="{FLOOR_STROKE * 100:.1f}"'
        ' stroke-linecap="round"/>\n'
        '</svg>\n')


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    (OUT / "favicon.svg").write_text(svg())
    # One .ico carrying every small size: the bare /favicon.ico request browsers
    # make on their own has no way to ask for a particular one.
    draw(256).save(OUT / "favicon.ico", sizes=[(n, n) for n in SIZES])
    draw(180).save(OUT / "apple-touch-icon.png")      # iOS home screen
    print("wrote favicon.svg, favicon.ico ({} sizes), apple-touch-icon.png"
          .format(len(SIZES)))
